@extends('layouts.main')

@section('title', 'Report Cards')
@section('header')
<link rel="stylesheet" href="{{ asset('css/select2.min.css') }}">
@endsection

@section('content')
<div class="container-fluid">
    <div class="row mb-3">
        <div class="col-md-6">
            <h3 class="m-0">
                <i class="fas fa-address-card mr-2"></i>
                Report Cards
            </h3>
        </div>
        <div class="col-md-6 text-right">
            <a href="{{ route('report-cards.create') }}" class="btn btn-success">
                <i class="fas fa-plus mr-2"></i>
                Generate Report Card
            </a>
            <button type="button" class="btn btn-info ml-2" data-toggle="modal" data-target="#bulkGenerateModal">
                <i class="fas fa-layer-group mr-2"></i>
                Bulk Generate
            </button>
        </div>
    </div>

    <!-- Filters -->
    <div class="card card-outline card-primary">
        <div class="card-header">
            <h3 class="card-title">Filters</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('report-cards.index') }}" method="GET">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Student</label>
                            <select name="student_id" class="form-control select2">
                                <option value="">All Students</option>
                                @foreach($students ?? [] as $student)
                                    <option value="{{ $student->id }}" {{ request('student_id') == $student->id ? 'selected' : '' }}>
                                        {{ $student->full_name }} ({{ $student->admission_number }})
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Date From</label>
                            <input type="date" name="from_date" class="form-control" value="{{ request('from_date') }}">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label>Date To</label>
                            <input type="date" name="to_date" class="form-control" value="{{ request('to_date') }}">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 text-right">
                        <button type="submit" class="btn btn-primary">
                            <i class="fas fa-filter mr-2"></i>
                            Apply Filters
                        </button>
                        <a href="{{ route('report-cards.index') }}" class="btn btn-default ml-2">
                            <i class="fas fa-undo mr-2"></i>
                            Reset
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <!-- Report Cards Table -->
    <div class="card card-outline card-secondary">
        <div class="card-header">
            <h3 class="card-title">Generated Report Cards</h3>
            <div class="card-tools">
                <span class="badge text-bg-primary">{{ $reportCards->total() }} records</span>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Student</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th>PDF</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($reportCards as $reportCard)
                            <tr>
                                <td>{{ $reportCard->id }}</td>
                                <td>
                                    <strong>{{ $reportCard->student->full_name ?? 'N/A' }}</strong>
                                    <br>
                                    <small class="text-muted">{{ $reportCard->student->admission_number ?? '' }}</small>
                                </td>
                                <td>{{ $reportCard->generatedBy?->name ?? 'N/A' }}</td>
                                <td>{{ $reportCard->generated_at?->format('d/m/Y H:i') }}</td>
                                <td>
                                    @if($reportCard->pdf_path)
                                        <span class="badge text-bg-success">Available</span>
                                    @else
                                        <span class="badge text-bg-secondary">Not Saved</span>
                                    @endif
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{ route('report-cards.show', $reportCard) }}" class="btn btn-sm btn-info" title="View">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a href="{{ route('report-cards.download', $reportCard) }}" class="btn btn-sm btn-success" title="Download PDF">
                                            <i class="fas fa-download"></i>
                                        </a>
                                        <form action="{{ route('report-cards.destroy', $reportCard) }}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure?');">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger" title="Delete">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6" class="text-center py-4 text-muted">
                                    <i class="fas fa-address-card fa-3x mb-3"></i>
                                    <br>
                                    No report cards found. Click "Generate Report Card" to create one.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer clearfix">
            {{ $reportCards->links() }}
        </div>
    </div>
</div>

<!-- Bulk Generate Modal -->
<div class="modal fade" id="bulkGenerateModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Bulk Generate Report Cards</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <span>&times;</span>
                </button>
            </div>
            <form action="{{ route('report-cards.bulk-generate') }}" method="POST">
                @csrf
                <div class="modal-body">
                    <div class="form-group">
                        <label for="class_id">Class <span class="text-danger">*</span></label>
                        <select name="class_id" id="class_id" class="form-control select2" required>
                            <option value="">Select Class</option>
                            @foreach($classes as $class)
                                <option value="{{ $class->id }}">{{ $class->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="term">Term <span class="text-danger">*</span></label>
                                <select name="term" id="term" class="form-control" required>
                                    @foreach($terms as $term)
                                        <option value="{{ $term->value }}">Term {{ $term->value }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label for="year">Year <span class="text-danger">*</span></label>
                                <select name="year" id="year" class="form-control" required>
                                    @foreach($years as $year)
                                        <option value="{{ $year }}">{{ $year }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-layer-group mr-2"></i>
                        Generate
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@section('javascript')
<script src="{{ asset('js/select2.full.min.js') }}"></script>
<script>
    $(document).ready(function() {
        $('.select2').select2({
            placeholder: "Select option",
            allowClear: true
        });
    });
</script>
@endsection
